name: Build Padavan Toolchain

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt install autoconf autoconf-archive automake autopoint bison build-essential \
        ca-certificates cmake cpio curl doxygen fakeroot flex gawk gettext git gperf help2man \
        htop kmod libblkid-dev libc-ares-dev libcurl4-openssl-dev libdevmapper-dev libev-dev \
        libevent-dev libexif-dev libflac-dev libgmp3-dev libid3tag0-dev libjpeg-dev libkeyutils-dev \
        libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libogg-dev libsqlite3-dev libssl-dev libtool \
        libtool-bin libudev-dev libvorbis-dev libxml2-dev locales mc nano pkg-config ppp-dev \
        python3 python3-docutils texinfo unzip uuid uuid-dev vim wget xxd zlib1g-dev
    - name: Clone source code
      env:
        KERNEL: 3.4
      run: |
        git clone --depth=1 https://gitlab.com/hadzhioglu/padavan-ng.git /opt/rt-n56u
        mkdir -p /opt/toolchain/
    - name: Building toolchain
      run: |
        cd /opt/rt-n56u/toolchain
        ./build_toolchain.sh
        cd /opt/rt-n56u/toolchain/out
        tar zcvf /opt/toolchain/mipsel-linux-uclibc.tar.xz .
    - name: Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-prebuilt-toolchain
        path: /opt/toolchain
